### ISSUE TITLE
dice-n1exe1-3 (microservice version)

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices#1]
**Process checklist:**

- [x] project structure (basic) h2 persistence and secure, based on microservice system, config server, eureka, gateway for Game, Player and Auth microservices
- [x] auth roles implementation (24/01/2024)
- [x] traces (no priority)

- [x] cover requirement on the model and controller (27/01/2024)
- [x] --> business logic (dice roller quick analysis.txt in comments)
- [x] ---> model requirements (Rest template)

- [x] ----> New branch "model-requirements (merged with rest-template)"
- [x] ----> Player entity/DTO requires: registrationDate; games; addGames method, successRate method; 
- [x] ------> creates this bug (pending to debug) @plopezgit #14 
- [x] ----> Game entity/DTO requires: result is byte (1-0); rollDice method; result method;

- [x] ----> New branch "rest-template"
- [x] ----> Feign maven dependency on player-service
- [x] ----> creates GameClient interface on player-service model
- [x] ----> GameClient injection on PlayerService and its methods
- [x] ----> PlayerController methods

- [x] h2>mysql>mongo (29/01/2024) (finished 1 day before so an additional branch to review pattern were created for 29/01/2024)
- [x] ----> New branch "pattern-review"
- [x] ------> Games (29/01/2024)
- [x] ------> Player (29/01/2024)

- [x] ----> New branch "response-review"
- [x] ---> enhances responses and exception #48 #49 #50 #51   (30/01/2024)
- [x] -----> in addition : #58 #65 #66  (Done: 30/01/2024-31/01/2024)
- [x] DTO arguments validations #75 #73 among others (31/01/2024)

- [x] ----> New branch "tests"
- [x] basic repository test #85 (01/02/2024)
- [x] service test (02/02/2024) #88 
- [x] controller test (03/02/2024) #96 
- [ ] adds games and auth service unit test #113 #114 #115 #116 #117 (date: to be defined)

- [x] ----> New branch "doc-openapi"
- [x] api documentation swagger #63 #101  #106 #107 #105 #104  (Done: 04/01/2024)

- [ ] **Bugs and improvements:**
#125 
#126 
#127 
#128 

**Extras:**

- [x] android client test with (client android integrates to GET /games without auth filters)https://square.github.io/retrofit/ (09/02/2024)
- [x] traces Zipkin/Micrometer server alternative (24/01/2024)

**Demo:**

- [x] delivery demo brief: #118

**Comment by plopezgit** [comment]
@plopezgit auth roles implementation (24/01/2024) :

Viewer - Role: user - Only access to GET

![Screen Shot 2024-01-24 at 11 52 17 AM](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/7e822292-08aa-4da0-85ea-e327924cb419)
![Screen Shot 2024-01-24 at 11 53 53 AM](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/cc84314d-6ff9-4468-b656-4ce8f6ac0ffe)

Admin - Role: admin - Everything
![Screen Shot 2024-01-24 at 12 05 39 PM](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/b49a6416-74e1-4677-b476-6da52d80cb97)

![Screen Shot 2024-01-24 at 12 05 15 PM](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/b90b6d06-fa06-4b73-b954-3fca9bd2ae40)

**Comment by plopezgit** [comment]
traces Zipkin/Micrometer server alternative:
![dice-roller-microservices-use-trace](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/1243ec07-0733-4911-8c5e-ed6161de25da)

**Comment by plopezgit** [comment]
cover requirement on the model and controller (27/01/2024) is completed :)

**known issue here:**
https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/issues/29

**Comment by plopezgit** [comment]
final endpoints list on postman folders, including auth



![Image](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/df7d6fec-f0cb-4c44-8652-4b1eac2b267b)
