### ISSUE TITLE
[Checklist] Security to access API JWT & Spring Security

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices#2]
- [x] Add dependencies: stater-security (spring), and Json Web Token

- [x] Security package

- [x] -- Clase WebSecurityConfig or similar(@ ) // https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter/

- [x] ---  SecurityFilterChain method return (@ Bean) ==== Secuencia de seguridad

- [x] ---  UserDetailsService  method return (@ Bean) ==== Cargar de usuario en memoria (InMemoryUserDetailsManage)

- [x] --- PasswordEncoder method returning a type of encoder ex. new BCryptPasswordEncoder (@ Bean)

- [x] Auth db persistance

- [x] -- Clase TokenHelper or similar

- [x] Clase AuthCredentials

- [x] Clase UserDetailsServiceImpl implements UserDetailsService

- [x] Clase UserDetailImpl implements UserDetails

- [x] Clase JWTAuthenticationFilter extends UsernamePasswordAuthenticationFilter

- [x] Clase JWTAuthorizationFilter

**Comment by plopezgit** [comment]
this version works on separated project

[Security v3.txt](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/files/14023012/Security.v3.txt)

**Comment by plopezgit** [comment]
Manage to implement security on dice roller initial microservice project:

Check: https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices

**Comment by plopezgit** [comment]
Still in QA until project had-off

**Comment by plopezgit** [comment]
A player rolling dice:



![Image](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/0ae6d9c9-437d-4cd3-b0ff-3d88e15bb035)
![Image](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/6ff3dd10-ebbf-4a2e-88f4-de3cd138ff67)
![Image](https://github.com/plopezgit/Sprint5_T1_SpringBoot_Dice_Roller_Microservices/assets/131781567/8d08c321-8b80-492c-bda9-02548aaf9bed)
